apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  SUPABASE_URL: "${SUPABASE_URL}"
  SECRET_KEY: "${SECRET_KEY}"
  GITHUB_TOKEN: "${GITHUB_TOKEN}"
  GITHUB_CLIENT_ID: "${GITHUB_CLIENT_ID}"
  GITHUB_CLIENT_SECRET: "${GITHUB_CLIENT_SECRET}"
  ANTHROPIC_API_KEY: "${ANTHROPIC_API_KEY}"