apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
stringData:
  SUPABASE_URL: "${SUPABASE_URL}"
  SECRET_KEY: "${SECRET_KEY}"
  GIT_TOKEN: "${GIT_TOKEN}"
  GIT_CLIENT_ID: "${GIT_CLIENT_ID}"
  GIT_CLIENT_SECRET: "${GIT_CLIENT_SECRET}"
  ANTHROPIC_API_KEY: "${ANTHROPIC_API_KEY}"