apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: __FRONTEND_IMAGE__
          ports:
            - containerPort: 80

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"

          env:
            - name: VITE_API_URL
              value: "/api"
            - name: VITE_GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: GIT_CLIENT_ID